### ISSUE TITLE
Multiple links under “Project resources” are throwing 404 error

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-dsl-py#31]
https://pypi.org/project/opensearch-dsl/1.0.0/

**Comment by vchrombie** [comment]
Hi @VachaShah, I'm not sure if the link checker was the aim of the issue.

From what I understand, the links on the page https://pypi.org/project/opensearch-dsl/ doesn't redirect. @VijayanB, could you please shed more light on this? Please feel free to correct me if I'm wrong.

Having absolute URLs instead of relative URLs in the README.md would fix this issue from the next package release.

**Comment by vchrombie** [comment]
This was somewhat fixed in opensearch-py, https://raw.githubusercontent.com/opensearch-project/opensearch-py/main/README.md

PR #34 was aimed to align the README.md with the above https://raw.githubusercontent.com/opensearch-project/opensearch-dsl-py/main/README.md.

**Comment by VachaShah** [comment]
Ah my bad I misunderstood! Reopening the issue.

**Comment by vchrombie** [comment]
The PR #34 is merged, the new package when released on PyPI wouldn't have this issue. I think this can be closed.

**Comment by VachaShah** [comment]
Thank you @vchrombie!
